version: 2.1

jobs:
  run_unit_tests_service:
    description: Run unit tests (service)
    docker:
      - image: cimg/base:2024.05
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test service
          command: cd service && docker build --target=test .

workflows:
  version: 2
  test:
    jobs:
      - run_unit_tests_service
