version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/base:2024.05

jobs:
  test_service:
    executor: maven-executor
    working_directory: /service
    steps:
      - checkout
      - run:
          name: Test service
          command: docker build --target test .

workflows:
  version: 2
  test:
    jobs:
      - test_service
